#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
import argparse
import os
import shlex
import shutil
import subprocess
import sys

if __name__ != "__main__":
    raise Exception(
        "This file is intended to be executed as an executable program. You cannot use it as a module."
        "To run this script, run the ./build_docs.py command"
    )

ROOT_PROJECT_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir))
ROOT_PACKAGE_DIR = os.path.join(ROOT_PROJECT_DIR, "airflow")
CONF_DIR = os.path.join(ROOT_PROJECT_DIR, "docs-providers")
PROVIDER_INIT_FILE = os.path.join(ROOT_PACKAGE_DIR, "providers", "__init__.py")


class DocsBuilder:
    def __init__(self, provider):
        super().__init__()
        self.provider = provider

    @property
    def build_dir(self):
        return os.path.join(ROOT_PROJECT_DIR, "docs-providers", "_build", self.provider)

    @property
    def docs_dir(self):
        return os.path.join(ROOT_PROJECT_DIR, "docs-providers", self.provider)

    @property
    def api_dir(self):
        return os.path.join(self.docs_dir, "_api")

    def clean_files(self) -> None:
        """Cleanup all artifacts generated by previous builds."""
        shutil.rmtree(self.api_dir, ignore_errors=True)
        shutil.rmtree(self.build_dir, ignore_errors=True)
        os.makedirs(self.api_dir, exist_ok=True)
        os.makedirs(self.build_dir, exist_ok=True)
        print(f"Recreated content of the ${self.build_dir} and ${self.api_dir} folders")
        # Bugs in sphinx-autoapi using metaclasses prevent us from upgrading to 1.3
        # which has implicit namespace support. Until that time, we make it look
        # like a real package for building docs
        with open(PROVIDER_INIT_FILE, "wt"):
            pass

    def build_sphinx_docs(self) -> None:
        """Build documentation for sphinx."""
        build_cmd = [
            "sphinx-build",
            "-b",  # builder to use
            "html",
            "-d",  # path for the cached environment and doctree files
            f"{self.build_dir}/doctrees",
            "-c",  # path where configuration file (conf.py) is located
            CONF_DIR,
            "--color",  # do emit colored output
            self.docs_dir,  # path to documentation source files
            f"{self.build_dir}/html",  # path to output directory
        ]
        print("Executing cmd: ", " ".join([shlex.quote(c) for c in build_cmd]))

        env = os.environ.copy()
        env['AIRFLOW_PROVIDER'] = self.provider
        completed_proc = subprocess.run(build_cmd, cwd=self.docs_dir, env=env)
        if completed_proc.returncode != 0:
            sys.exit(completed_proc.returncode)


def is_valid_provider_name(value):
    if not os.path.isdir(os.path.join(CONF_DIR, value)):
        return False
    if not os.path.isfile(os.path.join(CONF_DIR, value, 'index.rst')):
        return False
    return True


def get_list_providers():
    result = []
    for filename in os.listdir(CONF_DIR):
        if is_valid_provider_name(filename):
            result.append(filename)
    return result


all_providers = get_list_providers()

parser = argparse.ArgumentParser(description='Builds documentation and runs spell checking')
parser.add_argument(
    'providers',
    help='If you want to build a docs for all providers, pass "all"',
    choices=['all', *all_providers],
    nargs='+',
)

# parser.add_argument('--docs-only', dest='docs_only', action='store_true', help='Only build documentation')
# parser.add_argument(
#     '--spellcheck-only', dest='spellcheck_only', action='store_true', help='Only perform spellchecking'
# )

args = parser.parse_args()


def build_docs(provider):
    builder = DocsBuilder(provider)
    builder.clean_files()
    builder.build_sphinx_docs()


try:
    providers = all_providers if 'all' in args.providers else args.providers
    for name in all_providers:
        build_docs(name)

finally:
    shutil.rmtree(PROVIDER_INIT_FILE, ignore_errors=True)
