#!/usr/bin/env bash
set -x

echo "Build hook is running. IMAGE_NAME=${IMAGE_NAME}, DOCKER_REPO=${DOCKER_REPO}, CACHE_TAG=${CACHE_TAG}, DOCKERFILE_PATH=${DOCKERFILE_PATH}"

# Pull the image for image currently built if it exists
docker pull ${IMAGE_NAME} || true

# Pull the image for latest build if it exists
docker pull ${DOCKER_REPO}:latest || true

if [[ ${CACHE_TAG} == "latest-clean" || ${CACHE_TAG} =~ "release.*" ]]; then
    echo "Disabling cache"
    CACHE_SPEC="--no-cache"
else
    echo "Enabling cache"
    CACHE_SPEC="--cache-from ${IMAGE_NAME} --cache-from ${DOCKER_REPO}:latest"
fi

# Build the image using cached versions if present - both the branch/tag version and latest build can be used
# as cache source - docker will choose appropriate cache based on hashes of the files changed
docker build --pull --build-arg AIRFLOW_TAG=${CACHE_TAG} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} \
        ${CACHE_SPEC} .

echo "Build finished"
